### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by mrcsdl** [GoekhanDev/Rust-Drops-Grabber#1]
Is it possible to run your bot on a Raspberry pi? 

I can only use chromium right there. 

Would be super awesome!

**Comment by GoekhanDev** [comment]
I don't really know, since I never owned a pi. But it should be possible since selenium is only a driver. 
You need to be logged in to twitch with the selected profile. 

Good Luck!

**Comment by GoekhanDev** [comment]
They changed the website again, will update the tool soon!

**Comment by mrcsdl** [comment]
thanks!

**Comment by GoekhanDev** [comment]
Fixed the Scraping of https://twitch.facepunch.com/. The Tool should work now again. Have a great day.

**Comment by GoekhanDev** [comment]
https://github.com/GoekhanDev/Rust-Drops-Grabber/commit/e573bb8e257dfe153565c160f5995433d3786a34#diff-12771384da4b1d401ac56ddd87f3dc70623bfcfc44f49793d25bf30008869361

**Comment by GoekhanDev** [comment]
e573bb8e257dfe153565c160f5995433d3786a34
